// <auto-generated />
using BTL002.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTL002.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20251104180626_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTL002.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_chi_tiet");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia_ban");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer")
                        .HasColumnName("ma_don_hang");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer")
                        .HasColumnName("ma_sach");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("BTL002.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_danh_gia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("integer")
                        .HasColumnName("diem_danh_gia");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer")
                        .HasColumnName("ma_sach");

                    b.Property<string>("NgayDanhGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_danh_gia");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSach", "MaNguoiDung")
                        .IsUnique();

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("BTL002.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_danh_muc");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            MaDanhMuc = 1,
                            MoTa = "Sách văn học trong nước và nước ngoài",
                            TenDanhMuc = "Văn học"
                        },
                        new
                        {
                            MaDanhMuc = 2,
                            MoTa = "Sách về kinh doanh và kinh tế",
                            TenDanhMuc = "Kinh tế"
                        },
                        new
                        {
                            MaDanhMuc = 3,
                            MoTa = "Sách về lập trình và công nghệ thông tin",
                            TenDanhMuc = "Công nghệ"
                        },
                        new
                        {
                            MaDanhMuc = 4,
                            MoTa = "Sách phát triển bản thân",
                            TenDanhMuc = "Tâm lý - Kỹ năng sống"
                        },
                        new
                        {
                            MaDanhMuc = 5,
                            MoTa = "Sách dành cho trẻ em",
                            TenDanhMuc = "Thiếu nhi"
                        });
                });

            modelBuilder.Entity("BTL002.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_don_hang");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDonHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("NgayDatHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_dat_hang");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("BTL002.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_gio_hang");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer")
                        .HasColumnName("ma_sach");

                    b.Property<string>("NgayThem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_them");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaSach");

                    b.HasIndex("MaNguoiDung", "MaSach")
                        .IsUnique();

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("BTL002.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_nguoi_dung");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mat_khau");

                    b.Property<string>("NgayDangKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_dang_ky");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            DiaChi = "Việt Nam",
                            Email = "admin@bookstore.com",
                            HoTen = "Quản trị viên",
                            MatKhau = "Admin@123",
                            NgayDangKy = "2025-11-01",
                            SoDienThoai = "0000000000",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("BTL002.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNhaXuatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_nha_xuat_ban");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhaXuatBan"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dia_chi");

                    b.Property<string>("TenNhaXuatBan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ten_nha_xuat_ban");

                    b.HasKey("MaNhaXuatBan");

                    b.ToTable("NhaXuatBans");

                    b.HasData(
                        new
                        {
                            MaNhaXuatBan = 1,
                            DiaChi = "161B Lý Chính Thắng, Q.3, TP.HCM",
                            TenNhaXuatBan = "NXB Trẻ"
                        },
                        new
                        {
                            MaNhaXuatBan = 2,
                            DiaChi = "55 Quang Trung, Hai Bà Trưng, Hà Nội",
                            TenNhaXuatBan = "NXB Kim Đồng"
                        },
                        new
                        {
                            MaNhaXuatBan = 3,
                            DiaChi = "96 Định Công, Hoàng Mai, Hà Nội",
                            TenNhaXuatBan = "NXB DH Mở Hà Nội"
                        },
                        new
                        {
                            MaNhaXuatBan = 4,
                            DiaChi = "175 Giảng Võ, Đống Đa, Hà Nội",
                            TenNhaXuatBan = "NXB Lao Động"
                        },
                        new
                        {
                            MaNhaXuatBan = 5,
                            DiaChi = "46 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội",
                            TenNhaXuatBan = "NXB Thế Giới"
                        });
                });

            modelBuilder.Entity("BTL002.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_sach");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSach"));

                    b.Property<decimal>("GiaBan")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("gia_ban");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hinh_anh");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("integer")
                        .HasColumnName("ma_danh_muc");

                    b.Property<int>("MaNhaXuatBan")
                        .HasColumnType("integer")
                        .HasColumnName("ma_nha_xuat_ban");

                    b.Property<int>("MaTacGia")
                        .HasColumnType("integer")
                        .HasColumnName("ma_tac_gia");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mo_ta");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("integer")
                        .HasColumnName("nam_xuat_ban");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong_ton");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ten_sach");

                    b.HasKey("MaSach");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNhaXuatBan");

                    b.HasIndex("MaTacGia");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("BTL002.Models.TacGia", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_tac_gia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ten_tac_gia");

                    b.Property<string>("TieuSu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tieu_su");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGias");

                    b.HasData(
                        new
                        {
                            MaTacGia = 1,
                            TenTacGia = "giang 01",
                            TieuSu = "Nhà văn nổi tiếng Việt Nam"
                        },
                        new
                        {
                            MaTacGia = 2,
                            TenTacGia = "giang 02",
                            TieuSu = "Tác giả người Mỹ về phát triển bản thân"
                        },
                        new
                        {
                            MaTacGia = 3,
                            TenTacGia = "giang 03",
                            TieuSu = "Doanh nhân và tác giả người Mỹ"
                        },
                        new
                        {
                            MaTacGia = 4,
                            TenTacGia = "giang 04",
                            TieuSu = "Nhà văn người Brazil"
                        },
                        new
                        {
                            MaTacGia = 5,
                            TenTacGia = "giang 05",
                            TieuSu = "Nhà văn Nhật Bản đương đại"
                        });
                });

            modelBuilder.Entity("BTL002.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ma_yeu_thich");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer")
                        .HasColumnName("ma_sach");

                    b.Property<string>("NgayThem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ngay_them");

                    b.HasKey("MaYeuThich");

                    b.HasIndex("MaSach");

                    b.HasIndex("MaNguoiDung", "MaSach")
                        .IsUnique();

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("BTL002.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("BTL002.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL002.Models.Sach", "Sach")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BTL002.Models.DanhGia", b =>
                {
                    b.HasOne("BTL002.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL002.Models.Sach", "Sach")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BTL002.Models.DonHang", b =>
                {
                    b.HasOne("BTL002.Models.NguoiDung", "NguoiDung")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("BTL002.Models.GioHang", b =>
                {
                    b.HasOne("BTL002.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL002.Models.Sach", "Sach")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BTL002.Models.Sach", b =>
                {
                    b.HasOne("BTL002.Models.DanhMuc", "DanhMuc")
                        .WithMany("Sachs")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTL002.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Sachs")
                        .HasForeignKey("MaNhaXuatBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BTL002.Models.TacGia", "TacGia")
                        .WithMany("Sachs")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("BTL002.Models.YeuThich", b =>
                {
                    b.HasOne("BTL002.Models.NguoiDung", "NguoiDung")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BTL002.Models.Sach", "Sach")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BTL002.Models.DanhMuc", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("BTL002.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("BTL002.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("BTL002.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("BTL002.Models.Sach", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("BTL002.Models.TacGia", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
